name: Sincronización Salesforce PRE con GitHub

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Salesforce CLI
        run: |
          sfdx --version
          sf --version

      - name: Authenticate Salesforce Org
        shell: cmd
        run: |
          echo %SF_AUTH_URL% > auth.txt
          sfdx auth:sfdxurl:store -f auth.txt -a PRE
          del auth.txt
        env:
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}

      - name: Show working directory and files
        shell: cmd
        run: |
          echo Current directory:
          cd
          echo -------------------
          dir /s

      - name: Retrieve metadata from Salesforce
        shell: cmd
        run: |
          echo Workspace: %GITHUB_WORKSPACE%
          sf project retrieve start --manifest "%GITHUB_WORKSPACE%\manifest\package.xml" --target-org PRE

      - name: Commit and push changes
        shell: cmd
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Salesforce Sync Bot"
          git add .
          git diff --cached --quiet || git commit -m "Sync from PRE %DATE% %TIME%"
          git push
