name: Sincronización Salesforce PRE con GitHub

on:
  schedule:
    - cron: "0 3 * * *" # Todos los días a las 03:00 UTC (04:00 en España)
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted

    steps:
      # ✅ 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ 2. Comprobar o instalar Salesforce CLI
      - name: Check or Install Salesforce CLI
        shell: powershell
        run: |
          if (-not (Get-Command sf -ErrorAction SilentlyContinue)) {
            Write-Host "Salesforce CLI not found. Installing..."
            npm install --global @salesforce/cli
          }
          # Persistir la ruta para steps siguientes
          echo "$env:APPDATA\npm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # Actualizar PATH en este mismo step
          $env:PATH += ";$env:APPDATA\npm"
          Write-Host "PATH actualizado: $env:PATH"
          sf --version


      # ✅ 3. Autenticación con SF_AUTH_URL
      - name: Authenticate Salesforce Org
        shell: cmd
        run: |
          echo %SF_AUTH_URL% > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias PRE --set-default
          del auth.txt
        env:
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}

      # ✅ 4. Crear estructura DX
      - name: Ensure Salesforce project structure
        shell: cmd
        run: |
          if not exist force-app mkdir force-app
          if not exist force-app\main mkdir force-app\main
          if not exist force-app\main\default mkdir force-app\main\default

      # ✅ 5. Crear manifest si no existe
      - name: Ensure manifest exists
        shell: cmd
        run: |
          if not exist manifest mkdir manifest
          if not exist manifest\package.xml (
            echo ^<?xml version="1.0" encoding="UTF-8"?^> > manifest\package.xml
            echo ^<Package xmlns="http://soap.sforce.com/2006/04/metadata"^> >> manifest\package.xml
            echo     ^<!-- Código --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ApexClass^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ApexTrigger^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ApexPage^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ApexComponent^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Lightning --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>LightningComponentBundle^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>AuraDefinitionBundle^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Objetos y Configuración --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>CustomObject^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>CustomField^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>RecordType^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>CompactLayout^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ListView^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>FieldSet^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ValidationRule^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>WebLink^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>BusinessProcess^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Automatización --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>Flow^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>Workflow^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>WorkflowAlert^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>WorkflowFieldUpdate^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>WorkflowRule^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>WorkflowTask^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ApprovalProcess^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>AssignmentRules^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>EscalationRules^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Seguridad --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>Profile^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>PermissionSet^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>Role^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>SharingRules^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Correo --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>EmailTemplate^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Reportes y Dashboards --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>Report^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>Dashboard^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>ReportType^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<!-- Configuración avanzada --^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>CustomMetadata^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>CustomApplication^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>StaticResource^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>RemoteSiteSetting^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<types^> >> manifest\package.xml
            echo         ^<members^>*^</members^> >> manifest\package.xml
            echo         ^<name^>NamedCredential^</name^> >> manifest\package.xml
            echo     ^</types^> >> manifest\package.xml
            echo     ^<version^>59.0^</version^> >> manifest\package.xml
            echo ^</Package^> >> manifest\package.xml
          )

      # ✅ 6. Debug: Mostrar contenido
      - name: Show working directory and manifest
        shell: cmd
        run: |
          echo Current directory:
          cd
          echo -------------------
          dir /s manifest

      # ✅ 7. Recuperar metadata con sf
      - name: Retrieve metadata from Salesforce
        shell: cmd
        run: |
          echo Workspace: %GITHUB_WORKSPACE%
          sf project retrieve start --manifest "%GITHUB_WORKSPACE%\manifest\package.xml" --target-org PRE

      # ✅ 8. Check y install git    
      - name: Check or Install Git
        shell: powershell
        run: |
          if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
            Write-Host "Git not found. Installing..."
            choco install git -y
            # Agregar ruta binaria de Git al PATH para siguientes steps
            echo "C:\Program Files\Git\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } else {
            Write-Host "Git is already installed."
          }
          git --version

      # ✅ 9. Commit y push si hay cambios
      - name: Commit and push changes
        shell: cmd
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Salesforce Sync Bot"
          git add .
          git diff --cached --quiet || git commit -m "Sync from PRE %DATE% %TIME%"
          git push
