name: Sync Salesforce PRE with GitHub

on:
  schedule:
    - cron: "0 3 * * *" # Todos los días a las 03:00 UTC (04:00 en España)
  workflow_dispatch:

jobs:
  sync:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate Salesforce Org
        shell: pwsh
        run: |
          Set-Content -Path auth.txt -Value "${{ secrets.SF_AUTH_URL }}"
          sfdx auth:sfdxurl:store -f auth.txt -a PRE
          Remove-Item auth.txt

      - name: Retrieve metadata from Salesforce
        run: |
          mkdir -p force-app
          sfdx force:source:retrieve -x manifest/package.xml -u PRE

      - name: Commit and push changes
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Salesforce Sync Bot"
          git add .
          git diff --cached --quiet || git commit -m "Sync from PRE $(date)"
          git push
