name: Sincronización Salesforce PRE con GitHub

on:
  schedule:
    - cron: "0 3 * * *" # Todos los días a las 03:00 UTC (04:00 en España)
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted  # ✅ Usará cualquier runner self-hosted, no depende de etiquetas

    steps:
      # ✅ 1. Descargar el código del repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ 2. Verificar Salesforce CLI
      - name: Check Salesforce CLI
        run: |
          sfdx --version
          sf --version
          sfdx plugins --core

      # ✅ 3. Autenticación con secreto SF_AUTH_URL
      - name: Authenticate Salesforce Org
        shell: cmd
        run: |
          echo %SF_AUTH_URL% > auth.txt
          sfdx auth:sfdxurl:store -f auth.txt -a PRE
          del auth.txt
        env:
          SF_AUTH_URL: ${{ secrets.SF_AUTH_URL }}

      # ✅ 4. Crear estructura DX si no existe
      - name: Ensure Salesforce project structure
        shell: cmd
        run: |
          if not exist force-app mkdir force-app
          if not exist force-app\main mkdir force-app\main
          if not exist force-app\main\default mkdir force-app\main\default
          if not exist manifest mkdir manifest

      # ✅ 5. Debug: Listar archivos para confirmar manifest
      - name: List repo files
        run: dir /s

      # ✅ 6. Recuperar metadata con comando actualizado
      - name: Retrieve metadata from Salesforce
        run: |
          sf project retrieve start --manifest manifest/package.xml --target-org PRE

      # ✅ 7. Commit & push solo si hay cambios
      - name: Commit and push changes
        shell: cmd
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Salesforce Sync Bot"
          git add .
          git diff --cached --quiet || git commit -m "Sync from PRE %DATE% %TIME%"
          git push
